rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.1
  - 2.2.3
  - 2.3.0
  - 2.4.0
  - rbx-2
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
