before_install:
  - gem update --system
  - gem update bundler
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
  - rbx-2
  - ruby-head
  - jruby-9.1.17.0
  - jruby-9.2.6.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
